import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import * as jsPDF from 'jspdf';
import { AngularFirestore } from '@angular/fire/firestore';
import { AuthService } from './auth.service';
import {ActivatedRoute} from '@angular/router';

@Component
({
  // tslint:disable-next-line:component-selector
  selector: 'createPDF',
  templateUrl: './createPDF.component.html',
  styleUrls: ['./createPDF.component.css']
})

export class CreatePDFComponent implements OnInit
{
  @ViewChild('content') content: ElementRef;

  reportEnabled = true;
  claimForm;

  // Booleans for showing if an UnRequired value is used
  address2Used = false;
  address3Used = false;
  projectProblemsUsed = false;
  projectProblemsDifficultyUsed = false;
  projectProblemsSolvedUsed = false;

  constructor(private db: AngularFirestore, private authService: AuthService, private route: ActivatedRoute)
  {
    if (this.authService.isLoggedIn)
    {
      console.log('logged in');
    }
  }

  async ngOnInit(): Promise<any>
  {
    console.log('ngOnInit called');
    if (this.authService.isLoggedIn)
    {
      const user = await this.authService.getCurrentUserUid();
      const userUid = user.uid;

      console.log('ngOnInit is logged in');
      console.log(userUid);
      this.db.collection('users').doc(userUid).collection('claimForm')
        .doc(this.route.snapshot.params.id).valueChanges().subscribe(value =>
      {
        this.claimForm = value;
      });
    }
    else
    {
      console.log('ngOnInit not logged in');
    }
  }

  checkUnRequiredValues(): void
  {
    if (this.claimForm.addressLine2 === 'undefined_value')
    {
      this.address2Used = true;
    }
    if (this.claimForm.addressLine3 === 'undefined_value')
    {
      this.address3Used = true;
    }
    if (this.claimForm.projectProblems === 'undefined_value')
    {
      this.projectProblemsUsed = true;
    }
    if (this.claimForm.projectProblemsDifficulty === 'undefined_value')
    {
      this.projectProblemsDifficultyUsed = true;
    }
    if (this.claimForm.projectProblemsSolved === 'undefined_value')
    {
      this.projectProblemsSolvedUsed = true;
    }
  }

  testLog(): void
  {
    console.log(this.claimForm);
  }

  createPDF(): any
  {
    let doc = new jsPDF();

    const specialElementHandlers =
      {
        // tslint:disable-next-line:typedef
        '#editor'(element, renderer)
        {
          return true;
        }
      };

    const margins =
      {
      top: 15,
      bottom: 20,
      left: 15,
      right: 15,
      width: 180
    };

    const content = this.content.nativeElement;

    // doc.fromHTML(content.innerHTML, 15, 15,
    //   {
    //     width: 180,
    //     elementHandlers: specialElementHandlers
    //   },
    //   // tslint:disable-next-line:only-arrow-functions typedef
    //   function(dispose)
    //   {
    //     doc.save('test.pdf');
    //   }, margins);

    doc.fromHTML(content.innerHTML, 15, 15,
      {
        width: 180,
        elementHandlers: specialElementHandlers
      },
      // tslint:disable-next-line:only-arrow-functions typedef
      dispose =>
      {
        doc = this.addWaterMark(doc);
        doc.save('test.pdf');
      }, margins);

    // doc = this.addWaterMark(doc);
  }

  addWaterMark(doc): any
  {
    const totalPages = doc.internal.getNumberOfPages();

    for (let i = 0; i < totalPages; i++)
    {
      doc.setPage(i);
      const img = new Image();
      img.src = 'assets/img/test.png';
      doc.addImage(img, 'PNG', 40, 40, 75, 75);
      doc.setTextColor(150);
      doc.text(50, doc.internal.pageSize.height - 10, 'Generated by Maximum R&D');
    }
    return doc;
  }
}
